drop table if exists users, requests, items, bookings, comments;

create table if not exists users (
  user_id bigint generated by default as identity not null,
  name varchar(255) not null,
  email varchar(512) not null,
  constraint pk_user primary key (user_id),
  constraint UQ_USER_EMAIL unique (email)
);

create table if not exists requests (
  request_id bigint generated by default as identity not null,
  description varchar,
  requestor_id bigint references users (user_id) on delete cascade,
  constraint pk_request primary key (request_id)
);

create table if not exists items (
  item_id bigint generated by default as identity not null,
  name varchar(255) not null,
  description varchar not null,
  is_available boolean not null,
  owner_id bigint references users (user_id) on delete cascade not null,
  request_id bigint references requests (request_id) on delete cascade,
  constraint pk_item primary key (item_id)
);

create table if not exists bookings (
  booking_id bigint generated by default as identity not null,
  start_date timestamp without time zone not null,
  end_date timestamp without time zone not null,
  item_id bigint references items (item_id) on delete cascade not null,
  booker_id bigint references users (user_id) on delete cascade not null,
  status varchar not null,
  constraint pk_booking primary key (booking_id)
);

 create table if not exists comments (
   comment_id bigint generated by default as identity not null,
   text varchar not null,
   item_id bigint references items (item_id) on delete cascade not null,
   author_id bigint references users (user_id) on delete cascade not null,
   constraint pk_comment primary key (comment_id)
 );

